### ISSUE TITLE
Erro ortográfico

### ISSUE THREAD

**Issue by henrique11varela** [LaggyMcLagg/UFCD-5415---Web-Des.-e-Dev.---Proj.-Boutique#1]
No Readme.md onde tem:  
- **Funções or Métodos JS:**  simpleClass || pokemonCenas `(cammelCase);`  

deveria ser:  
- **Funções or Métodos JS:**  simpleClass || pokemonCenas `(camelCase);`

**Comment by LaggyMcLagg** [comment]
Tranquei. ;) mas agr já não quero mexer mais nesse ficheiro com ainda mais
um commit. Mas dps vou alterar. :)
